# Generated by Django 3.1.6 on 2021-02-09 18:23

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20210208_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyshourl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
